
export const START_FETCH_POST = 'START_FETCH_POST';
export const START_FETCH_USERS = 'START_FETCH_USERS'
export const START_FETCH_ALL_POSTS = 'START_FETCH_ALL_POSTS'

export const GET_DATA_FROM_FETCH = 'GET_DATA_FROM_FETCH';
export const GET_USERS_FROM_FETCH = 'GET_USERS_FROM_FETCH'
export const GET_ALL_POSTS_FROM_FETCH = 'GET_ALL_POSTS_FROM_FETCH'

export const SEARCH_POSTS = 'SEARCH_POSTS'
